# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token d4e60322d6011832002cb923cf12638a20eb2915

{
  "title": "Полка 123",
  "description": "Купе"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token c402f3b34a30ba8141399cad7ad0922f123b30c6

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

#удаление
DELETE {{baseUrl}}/advertisements/6/
Authorization: Token c402f3b34a30ba8141399cad7ad0922f123b30c6

