# Generated by Django 3.1.2 on 2022-04-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scopes_tag_scopes_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
