# Generated by Django 3.1.2 on 2022-04-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20220405_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopes',
            options={'ordering': ['-is_main', 'article'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
