# Generated by Django 3.1.2 on 2022-04-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20220408_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='updated_ad',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.CharField(max_length=10, verbose_name='Температура'),
        ),
    ]
