# Generated by Django 3.1.2 on 2022-04-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20220409_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='updated_ad',
        ),
    ]
